version: '3.8'

services:
    app:
        build: .
        ports:
            - "80:80"
            - "3306:3306"
        dns:
            - 1.1.1.1
            - 1.0.0.1
        volumes:
            - ./:/app
            - ./appdata/mysql:/app_data/mysql
            - ./appdata/influx/data:/app_data/influx/data
            - ./docker/my.cnf:/etc/my.cnf
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/php.ini:/etc/php83/php.ini
            - ./docker/php-fpm.conf:/etc/php83/php-fpm.conf
            - ./docker/influxdb.conf:/etc/influxdb.conf
            - ./docker/supervisord.conf:/etc/supervisord.conf
